//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Banneractivitypop_prefab
    {
        public const string BundleName = "banneractivitypop_prefab";
        public const string BANNERACTIVITYPOP = "BannerActivityPop";
    }
    public class Coinfx_prefab
    {
        public const string BundleName = "coinfx_prefab";
        public const string COINFX = "CoinFx";
        public const string STARFX = "StarFx";
    }
    public class Font
    {
        public const string BundleName = "font";
        public const string DEFAULTFONTASSET = "DefaultFontAsset";
        public const string FONTALL = "FontAll";
        public const string HANZI = "hanzi";
        public const string KOCHARACTER = "KoCharacter";
        public const string SOURCEHANSANSCNBOLD_SDF_BLUE = "SourceHanSansCN-Bold SDF Blue";
        public const string SOURCEHANSANSCNBOLD_SDF_GREEN = "SourceHanSansCN-Bold SDF Green";
        public const string SOURCEHANSANSCNBOLD_SDF_RED = "SourceHanSansCN-Bold SDF Red";
        public const string SOURCEHANSANSCNBOLD = "SourceHanSansCN-Bold";
    }
    public class Popdialogbox_prefab
    {
        public const string BundleName = "popdialogbox_prefab";
        public const string POPDIALOGBOX = "PopDialogBox";
    }
    public class Ranklevelatlas_spriteatlasv2
    {
        public const string BundleName = "ranklevelatlas_spriteatlasv2";
        public const string RANKLEVELATLAS = "RankLevelAtlas";
    }
    public class Sceneunlock1_prefab
    {
        public const string BundleName = "sceneunlock1_prefab";
        public const string SCENEUNLOCK1 = "SceneUnlock1";
    }
    public class Sceneunlock2_prefab
    {
        public const string BundleName = "sceneunlock2_prefab";
        public const string SCENEUNLOCK2 = "SceneUnlock2";
    }
    public class Sceneunlock3_prefab
    {
        public const string BundleName = "sceneunlock3_prefab";
        public const string SCENEUNLOCK3 = "SceneUnlock3";
    }
    public class Sceneunlock4_prefab
    {
        public const string BundleName = "sceneunlock4_prefab";
        public const string SCENEUNLOCK4 = "SceneUnlock4";
    }
    public class Sceneunlockguide_prefab
    {
        public const string BundleName = "sceneunlockguide_prefab";
        public const string PLOTUNLOCKGUIDE = "PlotUnlockGuide";
        public const string SCENEUNLOCKGUIDE = "SceneUnlockGuide";
    }
    public class Uibattlepasspay_prefab
    {
        public const string BundleName = "uibattlepasspay_prefab";
        public const string UIBATTLEPASSPAY = "UIBattlePassPay";
    }
    public class Uibegin_prefab
    {
        public const string BundleName = "uibegin_prefab";
        public const string UIBEGIN = "UIBegin";
    }
    public class Uibeginselect_prefab
    {
        public const string BundleName = "uibeginselect_prefab";
        public const string UIBEGINSELECT = "UIBeginSelect";
    }
    public class Uibuyitem_prefab
    {
        public const string BundleName = "uibuyitem_prefab";
        public const string UIBUYITEM = "UIBuyItem";
    }
    public class Uibuypacksuccess_prefab
    {
        public const string BundleName = "uibuypacksuccess_prefab";
        public const string UIBUYPACKSUCCESS = "UIBuyPackSuccess";
    }
    public class Uichooseavatar_prefab
    {
        public const string BundleName = "uichooseavatar_prefab";
        public const string UICHOOSEAVATAR = "UIChooseAvatar";
    }
    public class Uicontinue_prefab
    {
        public const string BundleName = "uicontinue_prefab";
        public const string UICONTINUE = "UIContinue";
    }
    public class Uidoublegiftadactivity_prefab
    {
        public const string BundleName = "uidoublegiftadactivity_prefab";
        public const string UIDOUBLEGIFTADACTIVITY = "UIDoubleGiftADActivity";
    }
    public class Uigamenode_prefab
    {
        public const string BundleName = "uigamenode_prefab";
        public const string UIGAMENODE = "UIGameNode";
    }
    public class Uigetcoin_prefab
    {
        public const string BundleName = "uigetcoin_prefab";
        public const string UIGETCOIN = "UIGetCoin";
    }
    public class Uiguideanimpop_prefab
    {
        public const string BundleName = "uiguideanimpop_prefab";
        public const string UIGUIDEANIMPOP = "UIGuideAnimPop";
    }
    public class Uiguidelevel1_prefab
    {
        public const string BundleName = "uiguidelevel1_prefab";
        public const string UIGUIDELEVEL1AND2 = "UIGuideLevel1And2";
    }
    public class Uihightoweractivity_prefab
    {
        public const string BundleName = "uihightoweractivity_prefab";
        public const string UIHIGHTOWERACTIVITY = "UIHighTowerActivity";
    }
    public class Uihightoweractivityentrance_prefab
    {
        public const string BundleName = "uihightoweractivityentrance_prefab";
        public const string UIHIGHTOWERACTIVITYENTRANCE = "UIHighTowerActivityEntrance";
    }
    public class Uilessstar_prefab
    {
        public const string BundleName = "uilessstar_prefab";
        public const string UILESSSTAR = "UILessStar";
    }
    public class Uimagicstreakactivity_prefab
    {
        public const string BundleName = "uimagicstreakactivity_prefab";
        public const string UIMAGICSTREAKACTIVITY = "UIMagicStreakActivity";
    }
    public class Uimagicstreakactivityentrance_prefab
    {
        public const string BundleName = "uimagicstreakactivityentrance_prefab";
        public const string UIMAGICSTREAKACTIVITYENTRANCE = "UIMagicStreakActivityEntrance";
    }
    public class Uimallturntable_prefab
    {
        public const string BundleName = "uimallturntable_prefab";
        public const string UIMALLTURNTABLE = "UIMallTurntable";
    }
    public class Uimask_prefab
    {
        public const string BundleName = "uimask_prefab";
        public const string UIMASK = "UIMask";
    }
    public class Uimorelife_prefab
    {
        public const string BundleName = "uimorelife_prefab";
        public const string UIMORELIFE = "UIMoreLife";
    }
    public class Uipaiditemsguide_prefab
    {
        public const string BundleName = "uipaiditemsguide_prefab";
        public const string UIPAIDITEMSGUIDE = "UIPaidItemsGuide";
    }
    public class Uipersonal_prefab
    {
        public const string BundleName = "uipersonal_prefab";
        public const string UIPERSONAL = "UIPersonal";
    }
    public class Uiprograssgiftadactivity_prefab
    {
        public const string BundleName = "uiprograssgiftadactivity_prefab";
        public const string UIPROGRASSGIFTADACTIVITY = "UIPrograssGiftADActivity";
    }
    public class Uipropmask_prefab
    {
        public const string BundleName = "uipropmask_prefab";
        public const string UIPROPMASK = "UIPropMask";
    }
    public class Uiranka_prefab
    {
        public const string BundleName = "uiranka_prefab";
        public const string UIRANKA = "UIRankA";
    }
    public class Uiremoveadadactivity_prefab
    {
        public const string BundleName = "uiremoveadadactivity_prefab";
        public const string UIREMOVEADADACTIVITY = "UIRemoveAdADActivity";
    }
    public class Uiretry_prefab
    {
        public const string BundleName = "uiretry_prefab";
        public const string UIRETRY = "UIRetry";
    }
    public class Uirocketactivity_prefab
    {
        public const string BundleName = "uirocketactivity_prefab";
        public const string UIROCKETACTIVITY = "UIRocketActivity";
    }
    public class Uirocketactivityentrance_prefab
    {
        public const string BundleName = "uirocketactivityentrance_prefab";
        public const string UIROCKETACTIVITYENTRANCE = "UIRocketActivityEntrance";
    }
    public class Uisepecialoffergift_prefab
    {
        public const string BundleName = "uisepecialoffergift_prefab";
        public const string UISPECIALOFFER = "UISpecialOffer";
    }
    public class Uishop_prefab
    {
        public const string BundleName = "uishop_prefab";
        public const string UISHOP = "UIShop";
    }
    public class Uistreakwinguide_prefab
    {
        public const string BundleName = "uistreakwinguide_prefab";
        public const string UIWINSTREAKREMOVEHIDE = "UIWinStreakRemoveHide";
    }
    public class Uitierrankactivity_prefab
    {
        public const string BundleName = "uitierrankactivity_prefab";
        public const string UITIERRANKACTIVITY = "UITierRankActivity";
    }
    public class Uitierrankactivityentrance_prefab
    {
        public const string BundleName = "uitierrankactivityentrance_prefab";
        public const string UITIERRANKACTIVITYENTRANCE = "UITierRankActivityEntrance";
    }
    public class Uivictory_prefab
    {
        public const string BundleName = "uivictory_prefab";
        public const string UIVICTORY = "UIVictory";
    }
    public class Uivolcanicactivity_prefab
    {
        public const string BundleName = "uivolcanicactivity_prefab";
        public const string UIVOLCANICACTIVITY = "UIVolcanicActivity";
    }
    public class Uivolcanicactivityentrance_prefab
    {
        public const string BundleName = "uivolcanicactivityentrance_prefab";
        public const string UIVOLCANICACTIVITYENTRANCE = "UIVolcanicActivityEntrance";
    }
}
